
name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run SSM command
        uses: aws-actions/aws-ssm-send-command@v1
        with:
          command: /home/ubuntu/deploy.sh
          ec2-instance-id: ${{ secrets.AWS_INSTANCE_ID }}
          region: ${{ secrets.AWS_REGION }}
